#!/usr/bin/env bun
/**
 * Indexer Agent - Deep codebase indexing with LLM
 * Creates a full file tree with descriptions
 */

import { spawn, execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, extname } from 'path';

const OUTPUT_FILE = ".pi/state/codebase-index.json";
const TREE_FILE = ".pi/state/file-tree.md";

function runCommand(cmd, cwd = process.cwd()) {
  try {
    return execSync(cmd, { encoding: "utf-8", cwd });
  } catch {
    return "";
  }
}

function getFileTree(cwd, maxDepth = 4) {
  const tree = [];
  const ignore = ["node_modules", ".git", "dist", "build", ".next", "coverage", "__pycache__"];
  
  function walk(dir, depth = 0, prefix = "") {
    if (depth > maxDepth) return;
    
    try {
      const entries = runCommand(`ls -la "${dir}"`, cwd).split("\n").slice(1).filter(Boolean);
      
      for (let i = 0; i < entries.length; i++) {
        const line = entries[i];
        const parts = line.split(/\s+/);
        if (parts.length < 8) continue;
        
        const name = parts[parts.length - 1];
        const isDir = line.startsWith("d");
        
        if (ignore.some(x => name.includes(x))) continue;
        if (name === "." || name === "..") continue;
        
        const fullPath = join(dir, name);
        const relPath = fullPath.replace(cwd + "/", "");
        
        if (isDir) {
          tree.push({ path: relPath, type: "directory", extension: "dir" });
          walk(fullPath, depth + 1);
        } else {
          const ext = extname(name);
          const size = parseInt(parts[4]) || 0;
          tree.push({ path: relPath, type: "file", extension: ext, size });
        }
      }
    } catch {}
  }
  
  walk(cwd);
  return tree;
}

async function runLLM(prompt) {
  return new Promise((resolve, reject) => {
    const proc = spawn('pi', ['-p', prompt], {
      cwd: process.cwd(),
      stdio: 'pipe'
    });
    
    let output = '';
    proc.stdout.on('data', (data) => { output += data.toString(); });
    proc.stderr.on('data', (data) => { output += data.toString(); });
    
    proc.on('close', (code) => {
      if (code === 0) resolve(output);
      else reject(new Error(output));
    });
  });
}

function generateTreeMarkdown(files) {
  const lines = ["# Codebase File Tree\n", "Generated by Indexer Agent\n"];
  
  const dirs = files.filter(f => f.type === "directory");
  const regularFiles = files.filter(f => f.type === "file");
  
  lines.push(`\n## Directories (${dirs.length})\n`);
  dirs.forEach(d => {
    lines.push(`- 📁 **${d.path}/**`);
  });
  
  lines.push(`\n## Files (${regularFiles.length})\n`);
  
  const byDir = {};
  regularFiles.forEach(f => {
    const dir = f.path.includes("/") ? f.path.split("/")[0] : ".";
    if (!byDir[dir]) byDir[dir] = [];
    byDir[dir].push(f);
  });
  
  Object.keys(byDir).sort().forEach(dir => {
    if (dir !== ".") {
      lines.push(`\n### ${dir}/\n`);
    }
    byDir[dir].forEach(f => {
      const ext = f.extension || "none";
      const size = f.size ? ` (${Math.round(f.size / 1024)}KB)` : "";
      const icon = getIcon(ext);
      lines.push(`- ${icon} \`${f.path}\`${size}`);
    });
  });
  
  return lines.join("\n");
}

function getIcon(ext) {
  const icons = {
    ".ts": "📘", ".tsx": "⚛️", ".js": "📜", ".jsx": "📜",
    ".py": "🐍", ".md": "📝", ".json": "📋", ".yaml": "📋", ".yml": "📋",
    ".css": "🎨", ".html": "🌐", ".sh": "⚡", ".mjs": "📜", ".cjs": "📜",
    ".rs": "🦀", ".go": "🐹", ".java": "☕", ".cpp": "⚙️", ".c": "⚙️",
    "none": "📄"
  };
  return icons[ext] || icons["none"];
}

async function analyzeWithLLM(files, cwd) {
  console.log("\n🤖 LLM analyzing codebase structure...\n");
  
  const fileList = files.slice(0, 100).map(f => `${f.type === "dir" ? "📁" : "📄"} ${f.path}`).join("\n");
  
  const prompt = `You are the Indexer Agent. Analyze this codebase structure and provide:
1. Main purpose of the project
2. Key directories and their purpose
3. Technology stack (languages, frameworks)
4. Important files to know about

File tree (partial):
${fileList}

Respond with a structured analysis.`;
  
  try {
    const analysis = await runLLM(prompt);
    return analysis;
  } catch (e) {
    return "LLM analysis failed - proceeding with raw data";
  }
}

async function main() {
  console.log("\n📇 Indexer Agent\n" + "─".repeat(40));
  console.log("Building complete codebase index...\n");
  
  const cwd = process.cwd();
  
  console.log("📡 Step 1: Running scout scanner...");
  try {
    runCommand(`just scanner scout`);
  } catch {}
  
  console.log("\n🌲 Step 2: Building file tree...");
  const files = getFileTree(cwd);
  console.log(`   Found ${files.length} items`);
  
  console.log("\n🤖 Step 3: LLM analysis...");
  const analysis = await analyzeWithLLM(files, cwd);
  
  console.log("\n📝 Step 4: Generating documentation...");
  
  mkdirSync(".pi/state", { recursive: true });
  
  const index = {
    generated: new Date().toISOString(),
    project: cwd.split("/").pop(),
    totalItems: files.length,
    directories: files.filter(f => f.type === "directory").length,
    files: files.filter(f => f.type === "file").length,
    tree: files,
    analysis
  };
  
  writeFileSync(OUTPUT_FILE, JSON.stringify(index, null, 2));
  
  const treeMarkdown = generateTreeMarkdown(files);
  writeFileSync(TREE_FILE, `# Codebase Index: ${cwd.split("/").pop()}\n\n${treeMarkdown}\n\n---\n\n## LLM Analysis\n\n${analysis}\n`);
  
  console.log("\n✅ Index complete!\n");
  console.log("📄 Output files:");
  console.log(`   ${OUTPUT_FILE}`);
  console.log(`   ${TREE_FILE}`);
  console.log(`\n📊 Stats: ${files.filter(f => f.type === "file").length} files, ${files.filter(f => f.type === "directory").length} directories`);
}

main();