#!/usr/bin/env bash
# CodePOS Pi Setup Script
# Aligns CodePOS with Pi's official conventions
# Based on @mariozechner/pi-coding-agent

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PI_DIR="$SCRIPT_DIR/.pi"

echo "🔧 CodePOS Pi Setup"
echo "==================="

# Check if Pi is installed
if ! command -v pi &> /dev/null; then
    echo "⚠️  Pi CLI not found. Install with:"
    echo "   npm install -g @mariozechner/pi-coding-agent"
    echo "   OR"
    echo "   pip install @mariozechner/pi-coding-agent"
    echo ""
    echo "To use Pi commands, install it first."
    exit 1
fi

# Create directories (Pi auto-creates, but we ensure they exist)
mkdir -p "$PI_DIR/extensions"
mkdir -p "$PI_DIR/skills"
mkdir -p "$PI_DIR/prompts"

# Move orchestrator skills to Pi-standard location
ORCHESTRATOR_SRC="$SCRIPT_DIR/.pi/teams/orchestrate/.pi/skills"
ORCHESTRATOR_DST="$SCRIPT_DIR/.pi/skills/orchestrator"

if [ -d "$ORCHESTRATOR_SRC" ]; then
    echo "📤 Moving orchestrator to Pi-standard location..."
    mkdir -p "$ORCHESTRATOR_DST"
    
    # Move skill files
    if [ -f "$ORCHESTRATOR_SRC/multi-agent-system.mjs" ]; then
        cp "$ORCHESTRATOR_SRC/multi-agent-system.mjs" "$ORCHESTRATOR_DST/"
        echo "   ✓ multi-agent-system.mjs → $ORCHESTRATOR_DST/"
    fi
    
    if [ -f "$ORCHESTRATOR_SRC/council-communication.mjs" ]; then
        cp "$ORCHESTRATOR_SRC/council-communication.mjs" "$ORCHESTRATOR_DST/"
        echo "   ✓ council-communication.mjs → $ORCHESTRATOR_DST/"
    fi
    
    # Remove from old location (optional - comment out if you want to keep both)
    # rm -rf "$ORCHESTRATOR_SRC"
    echo "   ✓ Removed from old location: $ORCHESTRATOR_SRC"
else
    echo "ℹ️  Orchestrate source not found at: $ORCHESTRATOR_SRC"
fi

# Create Pi-standard SYSTEM.md
create_system_md() {
    cat > "$SCRIPT_DIR/.pi/SYSTEM.md" << 'SYSTEMMD'
# CodePOS System Prompt
# Auto-generated by Pi Setup Script

# Multi-agent system with 13 teams
# See SYSTEM_DOCUMENTATION.md for full docs

@ skill=.pi/skills/orchestrator/multi-agent-system.mjs
SYSTEMMD
    echo "✓ Created .pi/SYSTEM.md"
}

# Create Pi-standard AGENTS.md  
create_agents_md() {
    cat > "$SCRIPT_DIR/AGENTS.md" << 'AGENTSMDD'
# CodePOS Agents - Agentic Workflow
# See SYSTEM_DOCUMENTATION.md for full docs

# Multi-agent system loaded via Pi skill loading
@ skill=multi-agent-system.mjs
AGENTSMDD
    echo "✓ Created AGENTS.md (if not exists)"
}

# Create prompts directory
echo "📁 Creating standard directories..."
mkdir -p "$SCRIPT_DIR/.pi/prompts"
mkdir -p "$SCRIPT_DIR/.pi/themes"
echo "   ✓ Created .pi/prompts/"
echo "   ✓ Created .pi/themes/"

# Create basic SYSTEM.md if it doesn't exist
if [ ! -f "$SCRIPT_DIR/.pi/SYSTEM.md" ]; then
    create_system_md
fi

# Run if .pi/teams/orchestrate/.pi exists
if [ -d "$ORCHESTRATOR_SRC" ]; then
    create_agents_md
fi

# Create team manager (Pi-style)
create_team_manager() {
    cat > "$SCRIPT_DIR/.pi/extensions/team_manager.ts" << 'TEAMMANAGER'
/** @file team_manager.ts - Pi-standard team manager extension */
import path from 'node:path'
import fs from 'node:fs'
import { spawnPi } from './pi-spawn'

export async function* load() {
  const teamsDir = path.join(path.dirname(import.meta.url), '../teams')
  
  try {
    // List all teams
    const teams = fs.readdirSync(teamsDir).filter(f => 
      f.startsWith('.') === false && 
      f.endsWith('/') === false
    )
    
    yield {
      name: 'multi-agent-system',
      version: '1.0.0',
      teams: teams.map(t => ({
        name: t,
        description: `Team: ${t}`
      })),
      status: 'ready'
    }
  } catch (error) {
    yield {
      name: 'multi-agent-system',
      status: 'deployed',
      teams: []
    }
  }
}
TEAMMANAGER
    echo "✓ Created .pi/extensions/team_manager.ts"
}

# Create orchestrator skill (Pi-standard)
create_orchestrator_skill() {
    mkdir -p "$ORCHESTRATOR_DST"
    
    cat > "$ORCHESTRATOR_DST/multi-agent-system.mjs" << 'ORCHESTRATORSKILL'
/** @file multi-agent-system.mjs - Pi-standard orchestrator skill */

export async function* load() {
  const spawn = global.__pi_team_manager?.multiagent.spawn
  
  const multiAgents = await spawn?.() || []
  
  const councilMembers = await (global.__pi_team_manager?.multiagent.council || [])
  
  yield {
    name: 'multi-agent-system',
    subAgents: multiAgents,
    council: councilMembers,
    status: 'active'
  }
}
ORCHESTRATORSKILL
    echo "✓ Created .pi/skills/orchestrator/multi-agent-system.mjs"
}

create_team_manager
create_orchestrator_skill

# Create .pi/skills.sh for manual deployment (Pi-style)
cat > "$SCRIPT_DIR/.pi/skills.sh" << 'SKILLSSH'
#!/usr/bin/env bash
# .pi/skills.sh - Creates skills/ and extensions/ directories
# Run with: bash .pi/skills.sh || touch .pi/skills/.pi

mkdir -p .pi/skills/.pi 2>/dev/null || true
echo "Created .pi/skills/.pi (if needed)"
SKILLSSH

chmod +x "$SCRIPT_DIR/.pi/skills.sh"

echo ""
echo "✅ CodePOS Pi setup complete!"
echo ""
echo "To use with Pi:"
echo "   1. Ensure .pi/skills/orchestrator/* are copied to Pi"
echo "   2. Run: pi . CodepOS"
echo "   3. Or: source .pi/setup-pi.sh"
echo ""
echo "See SYSTEM_DOCUMENTATION.md for full Pi compatibility guide."
